name: main_mamba_environment
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::seqtk
  - bioconda::bedtools
  - bioconda::bowtie2
  - bioconda::cutadapt
  - bioconda::fastqc
  - bioconda::macs3
  - bioconda::phantompeakqualtools
  - python=3.10
